# Generated by Django 4.2.18 on 2025-01-30 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='banner',
        ),
    ]
