# Generated by Django 4.2.18 on 2025-01-30 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_remove_recipe_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='media',
            field=models.ImageField(null=True, upload_to='recipes/images/'),
        ),
    ]
